name: budget
description: "STONE BUDGET"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  firebase_analytics: ^11.3.4
  firebase_crashlytics: ^4.1.4
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.2
  firebase_messaging: ^15.1.4
  fpdart: ^1.1.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.6.1
  touchable_opacity: ^1.2.0
  cached_network_image: ^3.4.1
  go_router: ^14.3.0
  dio: ^5.7.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner:
  riverpod_lint: ^2.6.2
  go_router_builder: ^2.7.1
  riverpod_generator:
  custom_lint:


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700